export const cheersList = [
    "¡Hola!",
    "¡Hello!",
    "¡Hi!",
    "¡Buenas tardes!",
    "¡Buenas noches!",
    "¡Buenos días!",
    "¡Buen día!",
    "¡Hola, ¿qué tal?!",
    "¡Hola, ¿cómo andás?!",
    "¡Hola, ¿todo bien?!",
    "¡Hola, ¿qué haces?!",
    "¡Hola, ¿cómo va?!",
    "¡Hola, ¿todo piola?!",
    "¡Hola, ¿qué onda?!",
    "¡Hola, ¿qué pasa?!",
    "¡Hola, ¿qué tal la vida?!",
    "¡Hola, ¿cómo te va?!",
    "¡Hola, ¿todo tranqui?!",
    "¡Hola, ¿cómo andamos?!",
    "¡Hola, ¿qué me contás?!",
    "¡Hola, ¿todo joya?!",
    "¡Hola, ¿cómo te trata la vida?!",
    "¡Hola, ¿todo de diez?!",
    "¡Hola, ¿qué andás haciendo?!",
    "¡Hola, ¿cómo pinta la semana?!",
    "¡Hola, ¿todo viento en popa?!",
    "¡Hola, ¿cómo amaneciste?!",
    "¡Hola, ¿todo bacano?!",
    "¡Hola, ¿qué hay de nuevo?!",
    "¡Hola, ¿todo en orden?!",
    "¡Hola, ¿cómo va el día?!",
    "¡Hola, ¿todo legal?!",
    "¡Hola, ¿qué se cuenta?!",
    "¡Hola, ¿cómo te fue?!",
    "¡Hola, ¿todo de maravilla?!",
    "¡Hola, ¿qué tal el finde?!",
    "¡Hola, ¿todo perfecto?!",
    "¡Hola, ¿cómo estás?!",
    "¡Hola, ¿todo bien por ahí?!",
    "¡Hola, ¿qué tal todo?!",
    ".",
    "Hola",
    "Hi",
    "Como estas",
    "todo bien?",
    "quien sos",

  ]